import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const tripDetailStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 44,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  backBtnText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  settingsButton: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  leaveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 48,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderColor: 'rgba(239, 68, 68, 0.3)',
    borderWidth: 1,
  },
  leaveBtnText: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '600',
  },
  headerCard: {
    backgroundColor: colors.surface,
    borderRadius: 8,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  tripTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textPrimary,
    flex: 1,
  },
  hostBadge: {
    backgroundColor: 'rgba(20, 184, 166, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  hostBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primaryLight,
  },
  tripDates: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  sharingToggleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1.5,
    marginBottom: 10,
  },
  badgeAlways: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(20, 184, 166, 0.12)',
  },
  badgeForeground: {
    borderColor: colors.warning,
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
  },
  badgeOff: {
    borderColor: colors.border,
  },
  sharingToggleInfo: {
    flex: 1,
    marginRight: 12,
  },
  sharingToggleTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  sharingToggleSub: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
    lineHeight: 16,
  },
  settingsNoticeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    borderColor: 'rgba(245, 158, 11, 0.3)',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    marginBottom: 14,
  },
  settingsNoticeIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  settingsNoticeText: {
    flex: 1,
    fontSize: 12,
    color: '#FBBF24',
    lineHeight: 16,
  },
  mapHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
    marginTop: 6,
  },
  mapSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  markStopHeaderBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  markStopHeaderBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '700',
  },
  inviteBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(99, 102, 241, 0.12)',
    borderRadius: 14,
    padding: 16,
    borderColor: 'rgba(99, 102, 241, 0.3)',
    borderWidth: 1,
    marginTop: 10,
    marginBottom: 16,
  },
  inviteInfo: {
    flex: 1,
  },
  inviteLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.secondaryLight,
    letterSpacing: 1,
  },
  inviteCode: {
    fontSize: 20,
    fontWeight: '900',
    color: colors.textPrimary,
    letterSpacing: 2,
    marginTop: 2,
  },
  shareBtn: {
    backgroundColor: colors.secondary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
  },
  shareBtnText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '700',
  },
  membersSection: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  realtimeTag: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.success,
  },
  memberFilters: {
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderRadius: 6,
    padding: 3,
    marginBottom: 14,
  },
  tripActionsSection: {
    marginTop: 28,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  tripActionsTitle: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 10,
  },
  memberFilter: {
    flex: 1,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  memberFilterSelected: { backgroundColor: colors.primary },
  memberFilterText: { color: colors.textSecondary, fontSize: 12, fontWeight: '700' },
  memberFilterTextSelected: { color: '#FFF' },
  membersList: {
    gap: 10,
  },
  memberCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBg,
    borderRadius: 12,
    padding: 12,
    borderColor: colors.border,
    borderWidth: 1,
  },
  memberAvatarCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  memberInitial: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFF',
  },
  memberMeta: {
    flex: 1,
  },
  memberNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  memberName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  youBadge: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primaryLight,
  },
  hostRoleBadge: {
    fontSize: 12,
    color: colors.secondaryLight,
  },
  memberJoinedDate: {
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 2,
  },
  sharingStatusPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  sharingStatusText: {
    fontSize: 11,
    fontWeight: '600',
  },
  sharingOn: {
    color: colors.success,
  },
  sharingOff: {
    color: colors.textMuted,
  },
  notFoundContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  notFoundText: {
    fontSize: 16,
    color: colors.textSecondary,
    marginBottom: 16,
  },
  pendingSyncBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    borderColor: 'rgba(245, 158, 11, 0.4)',
    borderWidth: 1.5,
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  pendingSyncBannerTextGroup: {
    flex: 1,
    marginRight: 10,
  },
  pendingSyncBannerTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FBBF24',
  },
  pendingSyncBannerSub: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  syncRetryBtn: {
    backgroundColor: colors.warning,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  syncRetryBtnText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '700',
  },
  startTripBtn: {
    backgroundColor: colors.success,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  startTripBtnText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '700',
  },
  endTripBtn: {
    backgroundColor: colors.danger,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  endTripBtnText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '700',
  },
  plannedNoticeCard: {
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    borderColor: 'rgba(245, 158, 11, 0.3)',
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    marginBottom: 14,
  },
  plannedNoticeTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FBBF24',
    marginBottom: 4,
  },
  plannedNoticeSub: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  completedNoticeCard: {
    backgroundColor: 'rgba(100, 116, 139, 0.15)',
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 14,
    marginBottom: 14,
  },
  completedNoticeTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  completedNoticeSub: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  memberActionsColumn: {
    alignItems: 'flex-end',
    gap: 4,
  },
  removeMemberBtn: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginTop: 4,
  },
  routeLeaderBtn: {
    backgroundColor: 'rgba(20, 184, 166, 0.14)',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
  },
  routeLeaderBtnText: { fontSize: 10, fontWeight: '700', color: colors.primaryLight },
  removeMemberBtnText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.danger,
  },
});
